export const PERMISSIONS = {
  catalogCategoriesRead: 'CATALOG_CATEGORIES_READ',
  catalogCategoriesWrite: 'CATALOG_CATEGORIES_WRITE',
  catalogProductsRead: 'CATALOG_PRODUCTS_READ',
  catalogProductsWrite: 'CATALOG_PRODUCTS_WRITE',
  operationalStructureRead: 'OP_STRUCTURE_READ',
  operationalStructureWrite: 'OP_STRUCTURE_WRITE',
  adminUsersRead: 'ADMIN_USERS_READ',
  adminUsersWrite: 'ADMIN_USERS_WRITE',
  adminRolesRead: 'ADMIN_ROLES_READ',
  adminRolesWrite: 'ADMIN_ROLES_WRITE',
  posSalesCreate: 'POS_SALES_CREATE',
  posSalesVoid: 'POS_SALES_VOID',
  reportsSalesRead: 'REPORTS_SALES_READ',
  inventoryStocksRead: 'INVENTORY_STOCKS_READ',
  inventoryMovementsRead: 'INVENTORY_MOVEMENTS_READ',
} as const;
